### ISSUE TITLE
Update Application View

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#104]
Depends on #103.

Add a deaggregation graph/report/download view to the application view. Add button to execute a calculation. Add select box to select an IMT. This should reflect/update the currently selected analysis' selected IMT.

**Comment by jmfee-usgs** [comment]
should this use the IMT that was already selected (if already selected)

**Comment by emartinez-usgs** [comment]
Depends on: https://github.com/usgs/hazdev-accordion/pull/13
