### ISSUE TITLE
IE d3 render strangeness

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-hazard-tool#120]
Sometimes legend and axis labels are hidden until interacting with the graph, and they still come and go.  See screen shot from Win7 IE10

**Comment by jmfee-usgs** [comment]
![screen shot 2015-11-12 at 17 11 10](https://cloud.githubusercontent.com/assets/1717896/11135267/99068398-8960-11e5-8077-6edab75998a7.png)

**Comment by emartinez-usgs** [comment]
A similar issue occurred on the usgs/earthquake-usdesign application. Ultimately it was decided to fix the SVG width and height attributes at render time since this would only have adverse effects if the user was re-sizing their window. This solution still works on various sized screens/devices.

**Comment by jdbrown-USGS** [comment]
might not be a problem
