### ISSUE TITLE
Update color scale for epsilon values

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#149]
Use a diverging color scale such as color brewer 11-class RdYIBu

**Comment by ehunter-usgs** [comment]
Color Brewer:
http://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=11

D3 Color Scales:
https://github.com/d3/d3-3.x-api-reference/blob/master/Ordinal-Scales.md
