### ISSUE TITLE
Include Alaska and HI Static Data (?)

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#151]
Data will be provide by @pmpowers-usgs prior to committing to this issue.

**Comment by pmpowers-usgs** [comment]
The data is available; link sent under separate email.

**Comment by ehunter-usgs** [comment]
We need to recover all the data that was lost from the FTP server.

**Comment by emartinez-usgs** [comment]
This was part of #163 (accidentally)
