### ISSUE TITLE
Improve Print Styles

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#155]
Group hazard plots together. Group Deaggregation plot and data together. Use page-breaks if necessary. Ensure a single plot is never split across two pages.

In general, make it look nice when printing.

**Comment by jdbrown-USGS** [comment]
break after curves, deag plot, summery data

**Comment by ehunter-usgs** [comment]
I'd wait until #192 is done to tackle this... I'll do it :)
