### ISSUE TITLE
Deaggregation rendering

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/earthquake-hazard-tool#166]
For a data request such as:
...nshmp-haz-ws/deagg/E2008/COUS/-121/43/SA1P0/760/2475

* The magnitude axis is not scaling to accommodate the range of magnitudes returned by the data (overflow to northeast). I can supply a broader fixed magnitude range, although it's probably preferable to scan the magnitudes in all dead data bins for the min and max.
* The distance axis is scaling, but the tick values are not clean. There likely is some d3 JS such as: `var xScale = d3.scale.linear() ...`. The scale object has `domain()` method/function that can have `.nice()` appended to it to force tick values to conform to integer values or at least cleaner floating point values.
* The 'contribution' (z) axis should also be scaled to an appropriate height based on the relative amplitudes of the contributions in each r-m bin. This, however, currently requires summing over the epsilon bins in each r-m bin. It may be easier for me to supply the total.

**Comment by jdbrown-USGS** [comment]
update epsilon legend rendering use '..' rather than ','

**Comment by jdbrown-USGS** [comment]
compute distance, mag, and z range based on data.

**Comment by pmpowers-usgs** [comment]
Autoscale all axes. Down the road we may want to  have fixed scales under certain conditions.

**Comment by jmfee-usgs** [comment]
work in progress:
https://github.com/jmfee-usgs/earthquake-hazard-tool/tree/issue-166

currently autoscales, and supports fixed scale, but need some logic to choose origin/lookAt values based on data extent.
