### ISSUE TITLE
Response spectrum value plot out of range

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/earthquake-hazard-tool#195]
at short periods in high hazard areas

**Comment by jdbrown-USGS** [comment]
calculate bound for min and max time horizon, set fixed scale based on largest extent.

**Comment by emartinez-usgs** [comment]
spoke with @ashumway-usgs ...

- Will restrict time horizon input to [0 .. 10000] years
- Will fix y-axis extent to [xMin .. f(0.0001)] where f(0.0001) is the largest ground motion among the returned hazard curves corresponding to an AFE of 0.0001 (or 10000 year time horizon).
