### ISSUE TITLE
Clean up layers control

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#53]
Remove options from layers control that are redundant with controls on other parts of the page.

This is lowish priority but a nice-to-have at some point once details are more clear.

**Comment by emartinez-usgs** [comment]
What about when in full-screen mode? This needs a touch more thought.

**Comment by jdbrown-USGS** [comment]
https://github.com/emartinez-usgs/earthquake-hazard-tool/pull/3
