### ISSUE TITLE
Clickable Faults

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#54]
When the faults are on the map, make them clickable. Clicking on a fault should open a Leaflet pop-up with data about the fault. Use the existing (separate) fault maps application as an example/template:

http://earthquake.usgs.gov/hazards/qfaults/map/hazfault2014.html

**Comment by emartinez-usgs** [comment]
http://earthquake.usgs.gov/hazards/qfaults/map/hazfault2008.html

**Comment by emartinez-usgs** [comment]
Try to abstract this to a generalized hazdev-leaflet project where we can put all generic leaflet utilities.

**Comment by emcwhirter-usgs** [comment]
There is an empty project on github `hazdev-leaflet`. I will build everything from scratch to create the utility. The source code for the examples is on ehpdevel.

**Comment by emcwhirter-usgs** [comment]
https://github.com/usgs/hazdev-leaflet/pull/1
