### ISSUE TITLE
Restrict site class options based on location

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#56]
- For locations <= -115 allow Vs30 <= 1150 (B).
- For locations >= -100 allow Vs30 760 or 2000 (B/C or A)
- For locations between -115 and -100, allow Vs30 760 only.

**Comment by emartinez-usgs** [comment]
Only restrict the graphical interface, do not restrict the web service (or data) itself.

**Comment by jdbrown-USGS** [comment]
Fixed commas
