### ISSUE TITLE
Graph Bugs

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#58]
- Ensure hazard curve legend should be empty when there is no hazard curve data.
- Ensure axis labels, titles, and default ticks are visible even when no data is available.

Default Ticks:
Hazard Curve --> x [1E-3, 3], y [1E-6, 1E-1]
Spectrum --> x [0, 5], y [0, 1]

**Comment by pmpowers-usgs** [comment]
I believe both static and dynamic services are providing axis labels; should we leave the plots blank and rely on the services, rather than having to hard code the strings in js?
