### ISSUE TITLE
Dynamic Web Service

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#61]
Work with Peter to ensure the web service conforms to the usage and data output API specifications.

**Comment by ehunter-usgs** [comment]
Emailed Peter, the web service is currently down.

**Comment by pmpowers-usgs** [comment]
The service has been updated to return results (curves) for multiple periods, both via requesting multiple periods in a query, or by omitting the 'imt' parameter. e.g.

http://igskcicgusclstr:8080/nshmp-haz-ws/HazardCurve?edition=E2008&region=WUS&longitude=-118.25&latitude=34.05&vs30=760

**Comment by emartinez-usgs** [comment]
Latest code can be found in my "combined" branch here: https://github.com/emartinez-usgs/nshmp-haz-ws/tree/combined

This has updates to the web service as required by the web application. Until all these updates are merged into the main master branch, we will deploy from my "combined" branch.
