### ISSUE TITLE
Dynamic Web Service Edition

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#63]
Add an option to the "Edition" drop down box for the 2008 and 2014 dynamic web service.

**Comment by emartinez-usgs** [comment]
Change order of listed editions top-down with most-recent first. Dynamic editions are considered newer than any corresponding revision. By default, select the latest revision for the latest edition; currently 2014 Rev 1.

**Comment by emcwhirter-usgs** [comment]
The database has a `displayorder` column for `edition`s. Should we use that to order these, or is that for something else?

**Comment by emartinez-usgs** [comment]
Yes, the `displayorder` column should be used to query the data in a specific order and return in in an ordered array as part of the metadata.

**Comment by jdbrown-USGS** [comment]
fixes usgs/earthquake-hazard-tool#63
