### ISSUE TITLE
Use Precss

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-hazard-tool#68]
Since we updated some of the dependencies for this project to use flexbox we dropped compass from those projects in favor of postcss with a precss plugin. Precss uses a slightly different syntax for mixins, and this is causing problems in earthquake-hazard-tool.

This project should be updated to use postcss with the precss plugin.

**Comment by emartinez-usgs** [comment]
When using the PointControl to set a location, the cursor should be the small red pin icon. Now that the leaflet css is inline, the selector ordering is incorrect and the cursor remains the grabber hand.

Also, do not repeatedly call `process.cwd()`, instead, create a local variable and assign it to the `process.cwd()` value and then use the local variable repeatedly.

Finally, update the dev dependencies as follows:

```
    "autoprefixer-core": "^5.2.1",
    "chai": "^3.2.0",
    "cssnano": "^2.6.1",
    "d3": "^3.5.6",
    "gateway": "^1.0.0",
    "grunt": "^0.4.5",
    "grunt-browserify": "^4.0.0",
    "grunt-cli": "^0.1.13",
    "grunt-concurrent": "^2.0.3",
    "grunt-connect-proxy": "^0.2.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-connect": "^0.11.2",
    "grunt-contrib-copy": "^0.8.1",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-uglify": "^0.9.2",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-mocha-phantomjs": "^1.0.2",
    "grunt-postcss": "^0.5.5",
    "hazdev-accordion": "usgs/hazdev-accordion.git",
    "hazdev-d3": "usgs/hazdev-d3.git",
    "hazdev-location-view": "usgs/hazdev-location-view.git",
    "hazdev-tablist": "usgs/hazdev-tablist.git",
    "hazdev-template": "usgs/hazdev-template.git",
    "hazdev-webutils": "usgs/hazdev-webutils.git",
    "http-rewrite-middleware": "^0.1.6",
    "ini": "^1.3.4",
    "leaflet": "^0.7.3",
    "mocha": "^2.2.5",
    "precss": "^0.3.0",
    "sinon": "^1.16.1"
```

**Comment by emartinez-usgs** [comment]
I merged the existing PR since it allows the project to build, but my comments still should be addressed in an additional pull request.
