### ISSUE TITLE
Disable Auto-Calculate

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-hazard-tool#98]
- Do not attempt to automatically calculate results when inputs change.
- Make it more clear to the user they must click calculate in order to view results.
- Make it clear subsequent changes are not immediately reflected until user clicks calculate again.
  - Potentially switch from "Calculate" to "Update"
  - Potentially clear results on input change.

**Comment by jmfee-usgs** [comment]
(or include the actual inputs used in the results output, and wait until user clicks update/calculate/cancel before changing results output)
